ibm_cloud_fail_over/__init__.py,sha256=wbhBYFgjpXRsLHxkrubPZXlQQAtVu9Nj75lazY0A67c,275
ibm_cloud_fail_over/ibm_cloud_fail_over.py,sha256=BZQwBDxJdKMq2k-YdkICfTHEm9Gaf-DXvNxD6NVFcbk,25065
ibm_cloud_fail_over-1.0.8.dist-info/METADATA,sha256=eNDJAvpUWYu5eqMRg1q4jGGVPc_p4JRiTclj4k4NxY0,7027
ibm_cloud_fail_over-1.0.8.dist-info/WHEEL,sha256=qtCwoSJWgHk21S1Kb4ihdzI2rlJ1ZKaIurTj_ngOhyQ,87
ibm_cloud_fail_over-1.0.8.dist-info/licenses/LICENSE,sha256=xx0jnfkXJvxRnG63LTGOxlggYnIysveWIZ6H3PNdCrQ,11357
ibm_cloud_fail_over-1.0.8.dist-info/RECORD,,
